### ISSUE TITLE
Java client is a beta version

### ISSUE THREAD

**Issue by JakeSCahill** [hazelcast/hazelcast-cloud-java-sample-client#17]
In the `5.0` branch, the POM includes a dependency to a beta version of the client:

```
<groupId>com.hazelcast</groupId>
<artifactId>hazelcast-enterprise</artifactId>
<version>5.0-BETA-2</version>
```

We should update this to 5.0.

The `master` branch also uses version 3, so I'm not sure what `master` is used for.

**Comment by mdumandag** [comment]
This has been fixed with https://github.com/hazelcast/hazelcast-cloud-java-sample-client/commit/f100ab186af2ecb0def3f9d5708f24dd564ebb7c
